In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

$\rho$

TODO: add matrix elements

In [3]:
rho1 = (1/3)*np.array([[1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]])

rho2 = (1/3)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, -1, -1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]]) 

rho3 = (1/2)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]]) 

rho = Qobj((1/3)*(rho1 + rho2 + rho3))

rho



Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.11111111 -0.11111111 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.16666667  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.16666667]]

# Hamiltonian

$H^{(8)}=H \otimes \mathbb I \otimes \mathbb I  + \mathbb I \otimes H \otimes \mathbb I + \mathbb I \otimes\mathbb I \otimes H$, where $H = \frac{1}{2} (\mathbb I - Z)$

In [4]:
I = np.eye(2)
Z = np.array([[1, 0], [0, -1]])
h = (1/2)*(I-Z)

H = np.kron(h, np.kron(I,I)) + np.kron(I, np.kron(h,I)) + np.kron(I, np.kron(I,h))
H = Qobj(H)
H

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3.]]

Initial energy of the state = $\frac{29}{18} = 1.611111..$

In [5]:
# Initial Energy of the state
E_init = (rho*H).tr()
E_init.real

1.6111111111111112

In [32]:
# minimum energy state
rho_p = np.zeros((8,8))
for i in range(2):
    rho_p[i][i] += 1/3

rho_p[2][2] = 1/6
rho_p[4][4] = 1/6
rho_p = Qobj(rho_p)
rho_p

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.33333333 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.16666667 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [34]:
E_min = (rho_p*H).tr()
E_min

0.6666666666666666

In [35]:
ergotropy = E_init - E_min
ergotropy

(0.9444444444444445+0j)

# Entangling measurements in computational basis

Bell states
\begin{align*}
       &\ket{\Phi_+}=\frac{1}{\sqrt{2}}\left(\ket{00}+\ket{11}\right);
       \ket{\Phi_-}=\frac{1}{\sqrt{2}}\left(\ket{00}-\ket{11}\right);\\
       &\ket{\Psi_+} = \frac{1}{\sqrt{2}}\left(\ket{01}+\ket{10}\right);
       \ket{\Psi_-} = \frac{1}{\sqrt{2}}\left(\ket{01}-\ket{10}\right).
   \end{align*}

In [65]:
phi_plus, phi_minus, psi_plus, psi_minus = bell_state('00'), bell_state('01'), bell_state('10'), bell_state('11')
phi_plus, phi_minus, psi_plus, psi_minus = Qobj(phi_plus.full()), Qobj(phi_minus.full()), Qobj(psi_plus.full()), Qobj(psi_minus.full())

Projectors
\begin{align*}
       &P_1=\ket{\Phi_+}\bra{\Phi_+}\otimes \mathbb{I}_2;~
       P_2=\ket{\Phi_-}\bra{\Phi_-}\otimes \mathbb{I}_2\\
       &P_3=\ket{\Psi_+}\bra{\Psi_+}\otimes \mathbb{I}_2;~
       P_4=\ket{\Psi_-}\bra{\Psi_-}\otimes \mathbb{I}_2
   \end{align*}

In [66]:
I2 = qeye(2)
P1,P2, P3, P4 = tensor(phi_plus*phi_plus.dag(), I2), tensor(phi_minus*phi_minus.dag(), I2), tensor(psi_plus*psi_plus.dag(), I2), tensor(psi_minus*psi_minus.dag(), I2)
P1, P2, P3, P4 = Qobj(P1.full()), Qobj(P2.full()), Qobj(P3.full()), Qobj(P4.full())
projectors = [P1, P2, P3, P4]


In [8]:
projectors[0]

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.5 0.  0.  0.  0.  0.  0.5]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.5 0.  0.  0.  0.  0.  0.5]]

# Measurements

In [9]:
collapsed_state, probabilities = qutip.measurement.measurement_statistics_povm(rho, projectors)
probabilities

[0.2777777777777779,
 0.2777777777777779,
 0.11111111111111116,
 0.3333333333333335]

In [10]:
P1*rho*P1

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.06944444 0.02777778 0.         0.         0.         0.
  0.06944444 0.02777778]
 [0.02777778 0.06944444 0.         0.         0.         0.
  0.02777778 0.06944444]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.06944444 0.02777778 0.         0.         0.         0.
  0.06944444 0.02777778]
 [0.02777778 0.06944444 0.         0.         0.         0.
  0.02777778 0.06944444]]

Average state after measurement is given by $\tilde \rho = \sum_i P_i \rho P_i$

In [37]:
rho_avg = P1*rho*P1 + P2*rho*P2 + P3*rho*P3 + P4*rho*P4
rho_avg

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.13888889  0.05555556  0.          0.          0.          0.
   0.          0.        ]
 [ 0.05555556  0.13888889  0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.11111111  0.05555556  0.         -0.05555556
   0.          0.        ]
 [ 0.          0.          0.05555556  0.11111111 -0.05555556 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.05555556  0.11111111  0.05555556
   0.          0.        ]
 [ 0.          0.         -0.05555556 -0.11111111  0.05555556  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.13888889  0.05555556]
 [ 0.          0.          0.          0.          0.          0.
   0.05555556  0.13888889]]

In [36]:
# energy of averge state
E_avg = (rho_avg*H).tr()
E_avg.real

1.5000000000000009

In [64]:
phi_plus.full()

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j]])

In [67]:
basis(4,0)*phi_plus.dag()

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0.70710678 0.         0.         0.70710678]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

In [77]:
# the d=4 basis states are given by basis(4, i) for i = 0,1,2,3
U_basis_change = basis(4,0)*phi_plus.dag() + basis(4,1)*phi_minus.dag() + basis(4,2)*psi_plus.dag() + basis(4,3)*psi_minus.dag()
U_basis_change = Qobj((tensor(U_basis_change, I2)).full())
U_basis_change

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=False
Qobj data =
[[ 0.70710678  0.          0.          0.          0.          0.
   0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.          0.          0.
   0.          0.70710678]
 [ 0.70710678  0.          0.          0.          0.          0.
  -0.70710678 -0.        ]
 [ 0.          0.70710678  0.          0.          0.          0.
  -0.         -0.70710678]
 [ 0.          0.          0.70710678  0.          0.70710678  0.
   0.          0.        ]
 [ 0.          0.          0.          0.70710678  0.          0.70710678
   0.          0.        ]
 [ 0.          0.          0.70710678  0.         -0.70710678 -0.
   0.          0.        ]
 [ 0.          0.          0.          0.70710678 -0.         -0.70710678
   0.          0.        ]]

In [80]:
# write down everything in the new basis
rho_prime = U_basis_change*rho*U_basis_change.dag()
H_prime = U_basis_change*H*U_basis_change.dag()


P1_prime = U_basis_change*P1*U_basis_change.dag()
P2_prime = U_basis_change*P2*U_basis_change.dag()
P3_prime = U_basis_change*P3*U_basis_change.dag()
P4_prime = U_basis_change*P4*U_basis_change.dag()

projectors_prime = [P1_prime, P2_prime, P3_prime, P4_prime]

collapsed_state_prime, probabilities_prime = qutip.measurement.measurement_statistics_povm(rho_prime, projectors_prime)
# print(probabilities_prime)

rho_avg_prime = P1_prime*rho_prime*P1_prime + P2_prime*rho_prime*P2_prime + P3_prime*rho_prime*P3_prime + P4_prime*rho_prime*P4_prime


In [85]:
rho_avg_prime

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.38888889e-01  5.55555556e-02 -9.49417869e-18 -3.79767148e-18
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 5.55555556e-02  1.38888889e-01 -3.79767148e-18 -9.49417869e-18
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.49417869e-18 -3.79767148e-18  1.38888889e-01  5.55555556e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.79767148e-18 -9.49417869e-18  5.55555556e-02  1.38888889e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.11111111e-01  6.65997741e-18 -7.59534295e-18 -3.61307550e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   8.53070850e-18  1.29533915e-33 -3.61307550e-18 -7.22615101e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -7.59534295e-18 -3.98226745e-18  1.11

In [89]:
# eigenvalues of the average state
rho_avg_prime.eigenstates()

(array([-7.28709859e-17,  4.24406679e-02,  8.33333333e-02,  8.33333333e-02,
         1.11111111e-01,  1.94444444e-01,  1.94444444e-01,  2.90892665e-01]),
 array([Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [-1.00000000e+00]
         [ 3.33066907e-16]
         [ 0.00000000e+00]]                                                   ,
        Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [ 0.00000000e+00]
         [-3.33066907e-16]
         [-8.50650808e-01]
         [ 5.25731112e-01]]                                                   ,
        Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
        Qobj data =
        [[ 

Haar Average state: $\tilde \rho = \sum_i p_i P_1/V_1$,

where $p_1 = Tr[P_1\rho]$

In [91]:
rho_haar_avg = (1/2)*(((P1_prime*rho_prime).tr()*P1_prime) + ((P2_prime*rho_prime).tr()*P2_prime) + ((P3_prime*rho_prime).tr()*P3_prime) + ((P4_prime*rho_prime).tr()*P4_prime))
rho_haar_avg

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 1.38888889e-01  0.00000000e+00 -9.49417869e-18  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.38888889e-01  0.00000000e+00 -9.49417869e-18
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-9.49417869e-18  0.00000000e+00  1.38888889e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -9.49417869e-18  0.00000000e+00  1.38888889e-01
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   5.55555556e-02  0.00000000e+00 -7.41074698e-18  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  5.55555556e-02  0.00000000e+00 -7.41074698e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -7.77993893e-18  0.00000000e+00  1.66

In [96]:
# eigenvalues of rho_haar_avg state
eig_values, eig_states = rho_haar_avg.eigenstates()
eig_states

array([Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
       Qobj data =
       [[0.]
        [0.]
        [0.]
        [0.]
        [1.]
        [0.]
        [0.]
        [0.]]                                                                ,
       Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
       Qobj data =
       [[0.]
        [0.]
        [0.]
        [0.]
        [0.]
        [1.]
        [0.]
        [0.]]                                                                ,
       Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
       Qobj data =
       [[0.]
        [1.]
        [0.]
        [0.]
        [0.]
        [0.]
        [0.]
        [0.]]                                                                ,
       Quantum object: dims=[[8], [1]], shape=(8, 1), type='ket', dtype=Dense
       Qobj data =
       [[0.]
        [0.]
        [0.]
        [1.]
        [0.]
        [0.]
        [0.]
        [0.

0.1388888888888889

Pauli Group

In [79]:
# Pauli matrices
I, X, Y, Z = qeye(2), sigmax(), sigmay(), sigmaz()

# Pauli group
pauli_group = []

for op in [I, X, Y, Z]:
    pauli_group.append(op)
    pauli_group.append(-1*op)
    pauli_group.append(1j*op)
    pauli_group.append(-1j*op)