In [2]:
import numpy as np
import matplotlib.pyplot as plt
from qutip import *

$\rho$

TODO: add matrix elements

In [3]:
rho1 = (1/3)*np.array([[1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [1, 1, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]])

rho2 = (1/3)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, -1, -1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, -1, 1, 1, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0]]) 

rho3 = (1/2)*np.array([[0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1]]) 

rho = Qobj((1/3)*(rho1 + rho2 + rho3))

rho



Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.11111111  0.11111111  0.11111111  0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.          0.11111111 -0.11111111 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.11111111  0.11111111  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.16666667  0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.16666667]]

# Hamiltonian

$H^{(8)}=H \otimes \mathbb I \otimes \mathbb I  + \mathbb I \otimes H \otimes \mathbb I + \mathbb I \otimes\mathbb I \otimes H$, where $H = \frac{1}{2} (\mathbb I - Z)$

In [4]:
I = np.eye(2)
Z = np.array([[1, 0], [0, -1]])
h = (1/2)*(I-Z)

H = np.kron(h, np.kron(I,I)) + np.kron(I, np.kron(h,I)) + np.kron(I, np.kron(I,h))
H = Qobj(H)
H

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3.]]

Initial energy of the state = $\frac{29}{18} = 1.611111..$

In [5]:
# Initial Energy of the state
E_init = (rho*H).tr()
E_init.real

1.6111111111111112

In [32]:
# minimum energy state
rho_p = np.zeros((8,8))
for i in range(2):
    rho_p[i][i] += 1/3

rho_p[2][2] = 1/6
rho_p[4][4] = 1/6
rho_p = Qobj(rho_p)
rho_p

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.33333333 0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.16666667 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.16666667 0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [34]:
E_min = (rho_p*H).tr()
E_min

0.6666666666666666

In [35]:
ergotropy = E_init - E_min
ergotropy

(0.9444444444444445+0j)

# Entangling measurements in computational basis

Bell states
\begin{align*}
       &\ket{\Phi_+}=\frac{1}{\sqrt{2}}\left(\ket{00}+\ket{11}\right);
       \ket{\Phi_-}=\frac{1}{\sqrt{2}}\left(\ket{00}-\ket{11}\right);\\
       &\ket{\Psi_+} = \frac{1}{\sqrt{2}}\left(\ket{01}+\ket{10}\right);
       \ket{\Psi_-} = \frac{1}{\sqrt{2}}\left(\ket{01}-\ket{10}\right).
   \end{align*}

In [6]:
phi_plus, phi_minus, psi_plus, psi_minus = bell_state('00'), bell_state('01'), bell_state('10'), bell_state('11')

Projectors
\begin{align*}
       &P_1=\ket{\Phi_+}\bra{\Phi_+}\otimes \mathbb{I}_2;~
       P_2=\ket{\Phi_-}\bra{\Phi_-}\otimes \mathbb{I}_2\\
       &P_3=\ket{\Psi_+}\bra{\Psi_+}\otimes \mathbb{I}_2;~
       P_4=\ket{\Psi_-}\bra{\Psi_-}\otimes \mathbb{I}_2
   \end{align*}

In [7]:
I2 = qeye(2)
P1,P2, P3, P4 = tensor(phi_plus*phi_plus.dag(), I2), tensor(phi_minus*phi_minus.dag(), I2), tensor(psi_plus*psi_plus.dag(), I2), tensor(psi_minus*psi_minus.dag(), I2)
P1, P2, P3, P4 = Qobj(P1.full()), Qobj(P2.full()), Qobj(P3.full()), Qobj(P4.full())
projectors = [P1, P2, P3, P4]


In [8]:
projectors[0]

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.5 0.  0.  0.  0.  0.  0.5]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0.  0.  0.5 0. ]
 [0.  0.5 0.  0.  0.  0.  0.  0.5]]

# Measurements

In [9]:
collapsed_state, probabilities = qutip.measurement.measurement_statistics_povm(rho, projectors)
probabilities

[0.2777777777777779,
 0.2777777777777779,
 0.11111111111111116,
 0.3333333333333335]

In [10]:
P1*rho*P1

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.06944444 0.02777778 0.         0.         0.         0.
  0.06944444 0.02777778]
 [0.02777778 0.06944444 0.         0.         0.         0.
  0.02777778 0.06944444]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.06944444 0.02777778 0.         0.         0.         0.
  0.06944444 0.02777778]
 [0.02777778 0.06944444 0.         0.         0.         0.
  0.02777778 0.06944444]]

Average state after measurement is given by $\tilde \rho = \sum_i P_i \rho P_i$

In [11]:
rho_avg = P1*rho*P1 + P2*rho*P2 + P3*rho*P3 + P4*rho*P4
rho_avg

Quantum object: dims=[[8], [8]], shape=(8, 8), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.13888889  0.05555556  0.          0.          0.          0.
   0.          0.        ]
 [ 0.05555556  0.13888889  0.          0.          0.          0.
   0.          0.        ]
 [ 0.          0.          0.11111111  0.05555556  0.         -0.05555556
   0.          0.        ]
 [ 0.          0.          0.05555556  0.11111111 -0.05555556 -0.11111111
   0.          0.        ]
 [ 0.          0.          0.         -0.05555556  0.11111111  0.05555556
   0.          0.        ]
 [ 0.          0.         -0.05555556 -0.11111111  0.05555556  0.11111111
   0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.13888889  0.05555556]
 [ 0.          0.          0.          0.          0.          0.
   0.05555556  0.13888889]]

In [ ]:
# energy of averge state
E_avg = (rho_avg*H).tr()
E_avg.real

Let, 
$$
\rho = \sum_{i,j}\rho_{ij}\ket i \bra j
$$
Now, we want to rewrite this in the basis $\{\ket{e_i}\}$. Then $\ket i = \sum_j \ket{e_j} \bra{e_j} \ket i$